version: '3'
services:

#############
  balance:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/balance_dataset.py --logging_level ${LOGGING:-INFO} --src_dataset trains_data  --src_table features_wo_testset --dst_dataset trains_data --dst_table features_balanced_test --no_balance

#############
  impute:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/impute_missing_values.py --logging_level ${LOGGING:-INFO}


#############
  rfr:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
    image: tervo/ml:cpu
    command: python -u bin/train_scikit.py --config_filename cnf/rf.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
#############
  lr:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_scikit.py --config_filename cnf/lr.ini --config_name  ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
#############
  gp:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
    image: tervo/gpflow
    command: python -u bin/train_gpflow.py --config_filename cnf/gp.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}


#############
  lstm:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_lstm.py --config_filename cnf/lstm.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}


  ############
  lstm_class:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/classify.py --config_filename cnf/lstm.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
  ############
  autoencoder:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_autoencoder.py --config_filename cnf/autoencoder.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
  ############
  class:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/classify_scikit.py --config_filename ${CONFIG_FILENAME:-cnf/rfc.ini} --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
  binary:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/classify_transactions_scikit.py --config_filename cnf/binary.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
  dual:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_dual.py --config_filename cnf/dual.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}



############
  vizperf:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      - HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/viz_performance.py --config_filename ${CONFIG_FILENAME:-cnf/rf.ini} --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO} --stations PSL,OL #,VS#--only_avg 1 #--stations PSL,OL #,VS
#############
  vizens:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      - HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/viz_performance_ensembles.py --config_filename ${CONFIG_FILENAME:-cnf/rf.ini} --config_name ${CONFIG_NAME:-16_params_1} --logging_level ${LOGGING:-INFO} --stations KAJ,OL #--endtime 2011-12-31 # --only_avg 1 #--stations PSL,OL,TPE,OV,PM,II,KEM,HKI --endtime 2011-12-31 #,VS
#############
  vis:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      - HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/visualize_data.py --dataset ${DATASET:-trains_2009_18_wo_testset} --starttime ${STARTTIME:-2010-01-01} --endtime ${ENDTIME:-2018-01-10} --logging_level ${LOGGING:-INFO} --save_path labels_vis_1_1 --what ${WHAT:-histograms}
#############
  feature_importance:
    volumes:
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-e3a33a82c833.json
    image: tervo/ml:cpu
    command: python -u bin/draw_rfr.py --logging_level ${LOGGING:-INFO} --model_file ${MODEL_FILE:-model/model.pkl} --parameters_filename cnf/forecast_parameters_shorten.txt

#############
  llasso:
    volumes:
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-e3a33a82c833.json
    image: tervo/ml:cpu
    command: python -u bin/train_scikit.py --logging_level ${LOGGING:-INFO} --config_filename ${CONFIG_FILENAME:-cnf/llasso.ini} --config_name ${CONFIG_NAME:-test}
#############
  test:
    volumes:
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-e3a33a82c833.json
    image: tervo/ml:cpu
    command: python -u bin/test.py --logging_level ${LOGGING:-INFO} --config_filename ${CONFIG_FILENAME:-cnf/llasso.ini} --config_name ${CONFIG_NAME:-test}
#############
  hist:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      - HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/histograms.py

#############
  feature_selection:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/feature_selection.py --config_filename cnf/lr.ini --config_name  ${CONFIG_NAME:-lasso_feature_selection} --logging_level ${LOGGING:-INFO}



#############
  board:
    volumes:
      - /tmp:/tmp
    ports:
      - "80:6006"
    image: tensorflow/tensorflow
    command: tensorboard --logdir=/tmp/lstm --host 0.0.0.0
#############
  pred:
    volumes:
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-e3a33a82c833.json
    image: docker.weatherproof.fi:5000/trains-prediction:1.2
    command: python -u bin/get_prediction_scikit.py --logging_level ${LOGGING:-INFO} --dev ${DEV:-1} --model_file ${MODEL_FILE:-model/model.pkl} --prec6h 0 --parameters_filename cnf/16_params_1.txt



  jup:
      volumes:
        - ~/Dropbox/tyot/trains:/home/jovyan/work
      environment:
        - GOOGLE_APPLICATION_CREDENTIALS=/home/jovyan/work/cnf/TRAINS-full.json
      image: tervo/pystan
      ports:
        - "80:8888"

  geopandas:
      volumes:
        - ~/Dropbox/tyot/trains:/home/jovyan/work
      environment:
        - GOOGLE_APPLICATION_CREDENTIALS=/home/jovyan/work/cnf/TRAINS-full.json
      image: tervo/geopandas
      ports:
        - "81:8888"
