version: '3'
services:
  get_as_csv:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      PYTHONUNBUFFERED: 1
    image: tervo/ml:cpu    
    command: python -u bin/get_as_csv.py --dataset ${DATASET:-trains-10d-sample} --type ${TYPE:-feature} --starttime 2018-01-07 --endtime 2018-01-08
#############
  create_db:
    image: tervo/ml:cpu
    command: python -u bin/ml_feature_db/db/create_db.py --force --logging_level DEBUG
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      PYTHONUNBUFFERED: 1
#############
  add_stations:
    image: tervo/ml:cpu
    command: python -u bin/add_locations.py --logging_level DEBUG --filename data/stations.json
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      PYTHONUNBUFFERED: 1
#############
  labels_from_csv:
    image: tervo/ml:cpu
    command: python -u bin/labels_from_csv.py --logging_level INFO --filename ${LABEL_FILE:-data/subset/a_b_nayte.csv} --dataset ${DATASET:-trains-10d-sample} --job_count 10 
    volumes:
      - ~:/root:ro
      - ~/trains:/a
#############
  remove_dataset:
    image: tervo/ml:cpu
    command: python -u bin/remove_dataset.py --logging_level INFO --labels --features --dataset ${DATASET:-trains-10d-sample}
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      PYTHONUNBUFFERED: 1
#############
  get_observations:
    image: tervo/ml:cpu
    command: python -u bin/get_observations.py --dataset ${DATASET:-trains-10d-sample} --producer opendata --starttime ${STARTTIME:-2018-01-01} --endtime ${ENDTIME:-2018-01-10} --job_count ${JOBS:-10} --logging_level ${LOGGING:-INFO}
    volumes:
      - ~:/root:ro
      - ~/trains:/a
#############
  get_observations_batch:
    image: tervo/ml:cpu
    command: python -u bin/get_observations_batch.py --dataset ${DATASET:-trains-10d-sample} --producer fmi --starttime ${STARTTIME:-2018-01-01} --endtime ${ENDTIME:-2018-01-10} --job_count ${JOBS:--1} --logging_level ${LOGGING:-INFO}
    volumes:
      - ~:/root:ro
      - ~/trains:/a
#############
  lr:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    image: tervo/ml:cpu    
    command: python -u bin/lr.py --dataset ${DATASET:-trains-10d-sample} --starttime ${STARTTIME:-2018-01-01} --endtime ${ENDTIME:-2018-01-10} --logging_level ${LOGGING:-INFO}
#############
  clean_db:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    image: tervo/ml:cpu_local    
    command: python -u bin/clean_duplicates.py --dataset ${DATASET:-trains-10d-sample} --logging_leve ${LOGGING:-INFO} --count 29
#############
  vis:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    image: tervo/ml:cpu
    command: python -u bin/visualize_data.py --dataset ${DATASET:-trains-10d-sample} --starttime ${STARTTIME:-2018-01-01} --endtime ${ENDTIME:-2018-01-10} --logging_level ${LOGGING:-INFO} --save_path labels_vis_1_0 --what ${WHAT:-histograms,history}
#############
  board:
    volumes:
      - /tmp:/tmp
    ports:
      - "6006:6006"
    image: tensorflow/tensorflow
    command: tensorboard --logdir=/tmp/lr --host 0.0.0.0
#############
  pred:
    volumes:
      - ~:/root
      - ~/trains:/a      
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-e3a33a82c833.json
    image: tervo/trains-prediction:1.0
    command: python -u bin/get_prediction.py --logging_level ${LOGGING:-INFO} 
    

