version: '3'
services:
  get_as_csv:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      PYTHONUNBUFFERED: 1
    image: tervo/ml:cpu
    command: python -u bin/get_as_csv.py --dataset ${DATASET:-trains-10d-sample} --type ${TYPE:-feature} --starttime 2018-01-07 --endtime 2018-01-08

#############
  add_stations:
    image: tervo/ml:cpu
    command: python -u bin/add_locations.py --logging_level DEBUG --filename data/stations.json
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      PYTHONUNBUFFERED: 1
#############
  labels_from_csv:
    image: tervo/ml:cpu
    command: python -u bin/labels_from_csv.py --logging_level INFO --filename ${LABEL_FILE:-data/subset/a_b_nayte.csv} --dataset ${DATASET:-trains-10d-sample} --job_count 10
    volumes:
      - ~:/root:ro
      - ~/trains:/a
#############
  remove_dataset:
    image: tervo/ml:cpu
    command: python -u bin/remove_dataset.py --logging_level INFO --labels --features --dataset ${DATASET:-trains-10d-sample}
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      PYTHONUNBUFFERED: 1
#############
  get_observations:
    image: tervo/ml:cpu
    command: python -u bin/get_observations.py --dataset ${DATASET:-trains-10d-sample} --producer opendata --starttime ${STARTTIME:-2018-01-01} --endtime ${ENDTIME:-2018-01-10} --job_count ${JOBS:-10} --logging_level ${LOGGING:-INFO}
    volumes:
      - ~:/root:ro
      - ~/trains:/a
#############
  get_observations_batch:
    image: tervo/ml:cpu
    command: python -u bin/get_observations_batch.py --dataset ${DATASET:-trains-1.0} --producer fmi --starttime ${STARTTIME:-2018-01-01} --endtime ${ENDTIME:-2018-01-10} --job_count ${JOBS:-4} --logging_level ${LOGGING:-INFO}
    volumes:
      - ~:/root:ro
      - ~/trains:/a
#############
  copy_dataset:
    image: tervo/ml:cpu
    command: python -u bin/copy_dataset.py --src_dataset ${SRC_DATASET:-trains-1.0} --dst_dataset ${DST_DATASET:-trains-1.2} --starttime ${STARTTIME:-2010-01-01} --endtime ${ENDTIME:-2013-01-10} --src_parameters ${SRC_PARAMETERS:-cnf/parameters.txt} --dst_parameters ${DST_PARAMETERS:-cnf/parameters_shorten.txt} --logging_level ${LOGGING:-INFO}
    volumes:
      - ~:/root:ro
      - ~/trains:/a


#############
  sep_testset:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/sep_testset.py --logging_level ${LOGGING:-INFO}

#############
  impute:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/impute_missing_values.py --logging_level ${LOGGING:-INFO} 


#############
  rfr:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
    image: tervo/ml:cpu
    command: python -u bin/train_scikit.py --config_filename cnf/rf.ini --config_name ${CONFIG_NAME:-all_all_1} --logging_level ${LOGGING:-INFO}
#############
  lr:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_scikit.py --config_filename cnf/lr.ini --config_name  ${CONFIG_NAME:-all_all_1} --logging_level ${LOGGING:-INFO}
#############
  svr:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_scikit.py --config_filename cnf/svr.ini --config_name  ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}

#############
  vizperf:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      - HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/viz_performance.py --logging_level ${LOGGING:-INFO} --feature_dataset ${FEATURE_DATASET:-trains_1y_dev} --model_path ${MODEL_PATH:-models/trains_1y_dev/serving/1530189858} --stations TKL,SAV #,VS
############
  vizperf_scikit:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      - HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/viz_performance.py --config_filename ${CONFIG_FILENAME:-cnf/lr.ini} --config_name ${CONFIG_NAME:-all_all_1} --logging_level ${LOGGING:-INFO} #--stations PSL,OL #,VS
#############
  vis:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    image: tervo/ml:cpu
    command: python -u bin/visualize_data.py --dataset ${DATASET:-trains-10d-sample} --starttime ${STARTTIME:-2018-01-01} --endtime ${ENDTIME:-2018-01-10} --logging_level ${LOGGING:-INFO} --save_path labels_vis_1_0 --what ${WHAT:-histograms,history}


#############
  board:
    volumes:
      - /tmp:/tmp
    ports:
      - "80:6006"
    image: tensorflow/tensorflow
    command: tensorboard --logdir=/tmp/lr --host 0.0.0.0
#############
  pred:
    volumes:
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-e3a33a82c833.json
    image: docker.weatherproof.fi:5000/trains-prediction:1.2
    command: python -u bin/get_prediction_scikit.py --logging_level ${LOGGING:-INFO} --dev ${DEV:-1} --model_file ${MODEL_FILE:-models/rf/trains_1y_dev/model.pkl}
