version: '3'
services:
  get_as_csv:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      PYTHONUNBUFFERED: 1
    image: tervo/ml:cpu
    command: python -u bin/get_as_csv.py --dataset ${DATASET:-trains-10d-sample} --type ${TYPE:-feature} --starttime 2018-01-07 --endtime 2018-01-08

#############
  add_stations:
    image: tervo/ml:cpu
    command: python -u bin/add_locations.py --logging_level DEBUG --filename data/stations.json
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      PYTHONUNBUFFERED: 1
#############
  labels_from_csv:
    image: tervo/ml:cpu
    command: python -u bin/labels_from_csv.py --logging_level INFO --filename ${LABEL_FILE:-data/subset/a_b_nayte.csv} --dataset ${DATASET:-trains-10d-sample} --job_count 10
    volumes:
      - ~:/root:ro
      - ~/trains:/a
#############
  remove_dataset:
    image: tervo/ml:cpu
    command: python -u bin/remove_dataset.py --logging_level INFO --labels --features --dataset ${DATASET:-trains-10d-sample}
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      PYTHONUNBUFFERED: 1
#############
  get_observations:
    image: tervo/ml:cpu
    command: python -u bin/get_observations.py --dataset ${DATASET:-trains-10d-sample} --producer opendata --starttime ${STARTTIME:-2018-01-01} --endtime ${ENDTIME:-2018-01-10} --job_count ${JOBS:-10} --logging_level ${LOGGING:-INFO}
    volumes:
      - ~:/root:ro
      - ~/trains:/a
#############
  get_observations_batch:
    image: tervo/ml:cpu
    command: python -u bin/get_observations_batch.py --dataset ${DATASET:-trains-1.0} --producer fmi --starttime ${STARTTIME:-2018-01-01} --endtime ${ENDTIME:-2018-01-10} --job_count ${JOBS:-4} --logging_level ${LOGGING:-INFO}
    volumes:
      - ~:/root:ro
      - ~/trains:/a
#############
  copy_dataset:
    image: tervo/ml:cpu
    command: python -u bin/copy_dataset.py --src_dataset ${SRC_DATASET:-trains-1.0} --dst_dataset ${DST_DATASET:-trains-1.2} --starttime ${STARTTIME:-2010-01-01} --endtime ${ENDTIME:-2013-01-10} --src_parameters ${SRC_PARAMETERS:-cnf/parameters.txt} --dst_parameters ${DST_PARAMETERS:-cnf/parameters_shorten.txt} --logging_level ${LOGGING:-INFO}
    volumes:
      - ~:/root:ro
      - ~/trains:/a


#############
  sep_testset:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/sep_testset.py --logging_level ${LOGGING:-INFO}

#############
  balance:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/balance_dataset.py --logging_level ${LOGGING:-INFO} --src_dataset trains_data  --src_table features_wo_testset --dst_dataset trains_data --dst_table features_balanced_test --no_balance

#############
  impute:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/impute_missing_values.py --logging_level ${LOGGING:-INFO}


#############
  rfr:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
    image: tervo/ml:cpu
    command: python -u bin/train_scikit.py --config_filename cnf/rf.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
#############
  lr:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_scikit.py --config_filename cnf/lr.ini --config_name  ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
#############
  svr:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_scikit.py --config_filename cnf/svr.ini --config_name  ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
#############
  ard:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_scikit.py --config_filename cnf/ard.ini --config_name  ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
#############
  gp:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
    image: tervo/gpflow
    command: python -u bin/train_gpflow.py --config_filename cnf/gp.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}


#############
  lstm:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_lstm.py --config_filename cnf/lstm.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}


  ############
  lstm_class:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/classify.py --config_filename cnf/lstm.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
  ############
  autoencoder:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_autoencoder.py --config_filename cnf/autoencoder.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
  ############
  class:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/classify_scikit.py --config_filename ${CONFIG_FILENAME:-cnf/rfc.ini} --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
  class_gmm:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/classify_scikit_gmm.py --config_filename ${CONFIG_FILENAME:-cnf/gmm_bgm.ini} --config_name ${CONFIG_NAME:-test_gmm} --logging_level ${LOGGING:-INFO}
  gmm:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_gmm.py --config_filename cnf/gmm_bgm.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}

  binary:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/classify_transactions_scikit.py --config_filename cnf/binary.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}
  dual:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_dual.py --config_filename cnf/dual.ini --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}

#############
  repr:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/train_representation.py --config_filename cnf/rf.ini --config_name  ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO}





############
  vizperf:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      - HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/viz_performance.py --config_filename ${CONFIG_FILENAME:-cnf/rf.ini} --config_name ${CONFIG_NAME:-test} --logging_level ${LOGGING:-INFO} --stations PSL,OL #,VS#--only_avg 1 #--stations PSL,OL #,VS
#############
  vizens:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      - HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/viz_performance_ensembles.py --config_filename ${CONFIG_FILENAME:-cnf/rf.ini} --config_name ${CONFIG_NAME:-16_params_1} --logging_level ${LOGGING:-INFO} --stations KAJ,OL #--endtime 2011-12-31 # --only_avg 1 #--stations PSL,OL,TPE,OV,PM,II,KEM,HKI --endtime 2011-12-31 #,VS
#############
  vis:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      - HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/visualize_data.py --dataset ${DATASET:-trains_2009_18_wo_testset} --starttime ${STARTTIME:-2010-01-01} --endtime ${ENDTIME:-2018-01-10} --logging_level ${LOGGING:-INFO} --save_path labels_vis_1_1 --what ${WHAT:-histograms}
#############
  feature_importance:
    volumes:
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-e3a33a82c833.json
    image: tervo/ml:cpu
    command: python -u bin/draw_rfr.py --logging_level ${LOGGING:-INFO} --model_file ${MODEL_FILE:-model/model.pkl} --parameters_filename cnf/forecast_parameters_shorten.txt
#############
  hist:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      - HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/histograms.py

#############
  feature_selection:
    volumes:
      - ~:/root:ro
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-full.json
      #- HTTPS_PROXY=wwwproxy.fmi.fi:8080
    image: tervo/ml:cpu
    command: python -u bin/feature_selection.py --config_filename cnf/lr.ini --config_name  ${CONFIG_NAME:-lasso_feature_selection} --logging_level ${LOGGING:-INFO}



#############
  board:
    volumes:
      - /tmp:/tmp
    ports:
      - "80:6006"
    image: tensorflow/tensorflow
    command: tensorboard --logdir=/tmp/lstm --host 0.0.0.0
#############
  pred:
    volumes:
      - ~/trains:/a
      - /tmp:/tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/a/cnf/TRAINS-e3a33a82c833.json
    image: docker.weatherproof.fi:5000/trains-prediction:1.2
    command: python -u bin/get_prediction_scikit.py --logging_level ${LOGGING:-INFO} --dev ${DEV:-1} --model_file ${MODEL_FILE:-model/model.pkl} --prec6h 0 --parameters_filename cnf/16_params_1.txt



  jup:
      volumes:
        - ~/Dropbox/tyot/trains:/home/jovyan/work
      environment:
        - GOOGLE_APPLICATION_CREDENTIALS=/home/jovyan/work/cnf/TRAINS-full.json
      image: tervo/pystan
      ports:
        - "80:8888"

  geopandas:
      volumes:
        - ~/Dropbox/tyot/trains:/home/jovyan/work
      environment:
        - GOOGLE_APPLICATION_CREDENTIALS=/home/jovyan/work/cnf/TRAINS-full.json
      image: tervo/geopandas
      ports:
        - "81:8888"
